services:
  authentication.api:
    image: ${DOCKER_REGISTRY-}authenticationapi
    build:
      context: .
      dockerfile: Authentication/Dockerfile
    ports:
     - "8080:8080"
     
  authentication.database:
      image: "postgres"
      environment:
        POSTGRES_PASSWORD: "NotSoVerySecret"
      volumes:
        - database.volume:/var/lib/postgresql
      ports:
        - "5432:5432"
      networks: 
        - default.network
      restart: always

volumes:
  databases.volume: